name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install
        run: |
          git config --global init.defaultBranch master
          sudo apt-get install cpanminus
          sudo cpanm --installdeps .
          cp CATS/Config.pm.template CATS/Config.pm

      - name: Run tests
        run: |
          prove
